version: '3.8'

services:
  # 이벤트 원본 로그와 결제 outbox 태스크를 저장합니다.
  postgres-db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - liveklass-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d liveklass_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 4가지 비즈니스 시나리오를 바탕으로 이벤트 로그를 지속 생성합니다.
  python-generator:
    build:
      context: ./generator
      dockerfile: Dockerfile
    container_name: liveklass_generator
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./analysis:/analysis
      - ./s3_data_lake:/s3_data_lake
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - liveklass-net

  # PostgreSQL 로그를 가상 S3 디렉토리로 백업하고 원본 데이터를 정리합니다.
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    image: liveklass_airflow:custom-2.7.2
    container_name: airflow
    environment:
      - AIRFLOW_CONN_POSTGRES_MAIN=${AIRFLOW_CONN_POSTGRES_MAIN}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres-db:5432/liveklass_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - S3_VIRTUAL_PATH=/opt/airflow/s3_data_lake
      - S3_VIRTUAL_PATH=/app/s3_data_lake
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./s3_data_lake:/app/s3_data_lake
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - liveklass-net
    command: >
      bash -c "airflow db migrate && 
      airflow users create --username admin --firstname Youngho --lastname Kim --role Admin --email admin@liveklass.co.kr --password admin && 
      (airflow scheduler &) && 
      airflow webserver"

networks:
  liveklass-net:
    driver: bridge

volumes:
  postgres_data:
