apiVersion: v1
kind: Secret
metadata:
  name: liveklass-db-secret
type: Opaque
stringData:
  POSTGRES_DB: liveklass_db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  DB_HOST: postgres-db
  DB_NAME: liveklass_db
  DB_USER: admin
  DB_PASSWORD: admin
  init.sql: |
    DROP TABLE IF EXISTS payment_tasks CASCADE;
    DROP TABLE IF EXISTS payment_details CASCADE;
    DROP TABLE IF EXISTS video_buffering_details CASCADE;
    DROP TABLE IF EXISTS cart_add_details CASCADE;
    DROP TABLE IF EXISTS page_view_details CASCADE;
    DROP TABLE IF EXISTS master_event_logs CASCADE;
    DROP TABLE IF EXISTS users CASCADE;

    CREATE TABLE users (
        user_id INT PRIMARY KEY,
        email VARCHAR(100) UNIQUE NOT NULL,
        name VARCHAR(50) NOT NULL,
        role VARCHAR(20) NOT NULL,
        joined_at TIMESTAMPTZ NOT NULL
    );

    CREATE TABLE master_event_logs (
        event_id UUID PRIMARY KEY,
        user_id INT NOT NULL,
        creator_id INT NOT NULL,
        event_type VARCHAR(50) NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT fk_master_user FOREIGN KEY (user_id) REFERENCES users(user_id),
        CONSTRAINT fk_master_creator FOREIGN KEY (creator_id) REFERENCES users(user_id)
    );

    CREATE TABLE page_view_details (
        event_id UUID PRIMARY KEY REFERENCES master_event_logs(event_id),
        lecture_id INT NOT NULL,
        referrer VARCHAR(100) NOT NULL
    );

    CREATE TABLE cart_add_details (
        event_id UUID PRIMARY KEY REFERENCES master_event_logs(event_id),
        lecture_id INT NOT NULL
    );

    CREATE TABLE video_buffering_details (
        event_id UUID PRIMARY KEY REFERENCES master_event_logs(event_id),
        lecture_id INT NOT NULL,
        buffering_duration INT NOT NULL,
        user_agent VARCHAR(255) NOT NULL
    );

    CREATE TABLE payment_details (
        event_id UUID PRIMARY KEY REFERENCES master_event_logs(event_id),
        order_id VARCHAR(100) UNIQUE NOT NULL,
        amount INT NOT NULL,
        status VARCHAR(20) NOT NULL,
        error_code VARCHAR(50)
    );

    CREATE TABLE payment_tasks (
        task_id BIGSERIAL PRIMARY KEY,
        order_id VARCHAR(100) NOT NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
        retry_count INT NOT NULL DEFAULT 0,
        updated_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT fk_tasks_payment_details FOREIGN KEY (order_id) REFERENCES payment_details(order_id)
    );
